services:
  postgres:
    image: postgres:latest
    container_name: evently-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pedro2012
      POSTGRES_USER: root
      POSTGRES_DB: evently
    ports:
      - '5432:5432'
    volumes:
      - evently-postgres-data:/var/lib/postgresql/data

volumes:
  evently-postgres-data:
